export enum FileActionTypes {

    API_RESPONSE_SUCCESS = '@@FILE/API_RESPONSE_SUCCESS',
    API_RESPONSE_ERROR = '@@FILE/API_RESPONSE_ERROR',

    Get_ALL_FILES = '@@FILE/Get_ALL_FILES',
    Get_BY_NAME_FILE = '@@FILE/Get_BY_NAME_FILE',
    UPDATE_FILE = '@@FILE/UPDATE_FILE',
    DELETE_FILE = '@@FILE/DELETE_FILE',
    CREATE_FILE = '@@FILE/CREATE_FILE',

}
